[package]
name = "MinWeb2025-blogging-platform-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
bson = "2.15.0"
mongodb = "3.2.3"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
uuid = { version = "1.0", features = ["serde", "v4"] }
